apiVersion: apps/v1
kind: Deployment
metadata:
  name: ago-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
      - name: argo-test
        image: "ramana96/jenkins-demo:1"
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
